const data = {
  prefixes: {
    "none": { meaning: "なし" },
    "a-": { meaning: "否定 (not, without)" },
    "ab-": { meaning: "～から離れて (from, off, away)" },
    "ad-": { meaning: "～の方へ (to, toward)" },
    "auto-": { meaning: "自己 (self)" },
    "com-": { meaning: "共に (with, together)" },
    "con-": { meaning: "共に (with, together)" },
    "contra-": { meaning: "反対に (against)" },
    "de-": { meaning: "離れて、下に、否定 (away, down, not)" },
    "dis-": { meaning: "分離、反対 (apart, not)" },
    "e-": { meaning: "外に (out, from)" },
    "ex-": { meaning: "外に (out of)" },
    "in-": { meaning: "中に、否定 (in, into, not)" },
    "inter-": { meaning: "間に (between, among)" },
    "intro-": { meaning: "内側へ (within, inward)" },
    "ob-": { meaning: "～に対して (against)" },
    "per-": { meaning: "通して、完全に (through, completely)" },
    "pre-": { meaning: "前に (before)" },
    "pro-": { meaning: "前に (forward)" },
    "re-": { meaning: "再び、後ろへ (again, back)" },
    "se-": { meaning: "離れて (apart)" },
    "sub-": { meaning: "下に (under)" },
    "super-": { meaning: "上に、超えて (above, beyond)" },
    "syn-": { meaning: "共に (with, together)" },
    "trans-": { meaning: "越えて (across, over)" },
    "un-": { meaning: "否定 (not)" },
  },
  roots: {
    "none": { meaning: "なし" },
    "act": { meaning: "行う (act, do)" },
    "cap / cept / ceive": { meaning: "取る (take, grasp)" },
    "ced / ceed / cess": { meaning: "行く、進む (go, yield)" },
    "clud / clus": { meaning: "閉じる (close, shut)" },
    "dic / dict": { meaning: "言う (say, speak)" },
    "duc / duct": { meaning: "導く (lead)" },
    "fac / fact / fect": { meaning: "作る、行う (make, do)" },
    "fer": { meaning: "運ぶ、もたらす (carry, bear)" },
    "fin": { meaning: "終わり (end, limit)" },
    "form": { meaning: "形作る (form, shape)" },
    "grad / gress": { meaning: "歩む、進む (step, go)" },
    "graph": { meaning: "書く (write)" },
    "ject": { meaning: "投げる (throw)" },
    "leg": { meaning: "法律 (law)" },
    "mit / miss": { meaning: "送る (send)" },
    "mov / mot": { meaning: "動く (move)" },
    "pel / puls": { meaning: "駆り立てる、押す (drive, push)" },
    "pend / pens": { meaning: "吊るす、重さをはかる (hang, weigh)" },
    "plic / ply": { meaning: "折り重ねる (fold)" },
    "pon / posit / pose": { meaning: "置く (put, place)" },
    "port": { meaning: "運ぶ (carry)" },
    "rupt": { meaning: "壊す (break)" },
    "scrib / script": { meaning: "書く (write)" },
    "sequ / secu": { meaning: "続く (follow)" },
    "spect": { meaning: "見る (look)" },
    "sta / sist / stit": { meaning: "立つ (stand)" },
    "tain / ten": { meaning: "保つ (hold)" },
    "tract": { meaning: "引く (draw, pull)" },
    "ven / vent": { meaning: "来る (come)" },
    "vert / vers": { meaning: "向ける (turn)" },
    "vis / vid": { meaning: "見る (see)" },
    "voc / voke": { meaning: "呼ぶ、声 (call, voice)" },
  },
  suffixes: {
    "none": { meaning: "なし" },
    "-able": { meaning: "～できる (able to)" },
    "-al": { meaning: "～の性質の (relating to)" },
    "-ance": { meaning: "～の状態 (state of)" },
    "-ant": { meaning: "～する人・物 (person/thing that)" },
    "-ate": { meaning: "～にする (to make)" },
    "-ence": { meaning: "～であること (state of)" },
    "-ent": { meaning: "～の性質の (having the quality of)" },
    "-ful": { meaning: "～に満ちた (full of)" },
    "-ic": { meaning: "～の性質の (relating to)" },
    "-ion": { meaning: "～すること (action of)" },
    "-ist": { meaning: "～する人 (person who)" },
    "-ity": { meaning: "～であること (state of)" },
    "-ive": { meaning: "～の性質を持つ (tending to)" },
    "-ize": { meaning: "～にする (to make)" },
    "-less": { meaning: "～のない (without)" },
    "-ment": { meaning: "～こと、もの (result of)" },
    "-or": { meaning: "～する人・物 (person or thing that)" },
    "-ous": { meaning: "～の性質の (full of)" },
    "-ure": { meaning: "～すること (action of)" },
  },
  words: [
    { prefix: "ab-", root: "rupt", suffix: "none", word: "abrupt", meaning: "突然の", etymology: "「離れて」＋「壊す」 → 突然何かが壊れるように起こること。" },
    { prefix: "ad-", root: "cap / cept / ceive", suffix: "none", word: "accept", meaning: "受け入れる", etymology: "「～の方へ」＋「取る」 → 差し出されたものを自分のほうに取ること。" },
    { prefix: "ad-", root: "mit / miss", suffix: "none", word: "admit", meaning: "認める", etymology: "「～の方へ」＋「送る」 → ある場所へ入ることを許可すること。" },
    { prefix: "ad-", root: "ven / vent", suffix: "-ure", word: "adventure", meaning: "冒険", etymology: "「～の方へ」＋「来る」＋「こと」 → 自分の方へやってくる出来事。" },
    { prefix: "ad-", root: "vert / vers", suffix: "none", word: "advert", meaning: "言及する", etymology: "「～の方へ」＋「向ける」 → 注意をそちらに向けること。" },
    { prefix: "ad-", root: "voc / voke", suffix: "-ate", word: "advocate", meaning: "主張する", etymology: "「～の方へ」＋「呼ぶ」 → 助けを求めて声をかけること。" },
    { prefix: "auto-", root: "graph", suffix: "none", word: "autograph", meaning: "サイン", etymology: "「自己」＋「書く」 → 自分で書いたもの。" },
    { prefix: "com-", root: "mit / miss", suffix: "-ment", word: "commitment", meaning: "約束", etymology: "「共に」＋「送る」＋「こと」 → 互いに心を送り合い、深く関わること。" },
    { prefix: "com-", root: "pel / puls", suffix: "none", word: "compel", meaning: "強制する", etymology: "「共に」＋「駆り立てる」 → 強い力で何かをさせること。" },
    { prefix: "com-", root: "pon / posit / pose", suffix: "none", word: "compose", meaning: "構成する", etymology: "「共に」＋「置く」 → 様々な要素を一緒に置いて組み立てること。" },
    { prefix: "com-", root: "tain / ten", suffix: "none", word: "contain", meaning: "含む", etymology: "「共に」＋「保つ」 → 中に一緒に保っていること。" },
    { prefix: "com-", root: "tract", suffix: "none", word: "contract", meaning: "契約", etymology: "「共に」＋「引く」 → 関係者をお互いに引き寄せること。" },
    { prefix: "con-", root: "clud / clus", suffix: "none", word: "conclude", meaning: "結論づける", etymology: "「完全に」＋「閉じる」 → 議論などを完全に閉じて結論を出す。" },
    { prefix: "con-", root: "fer", suffix: "-ence", word: "conference", meaning: "会議", etymology: "「共に」＋「運ぶ」＋「こと」 → 意見などを持ち寄ること。" },
    { prefix: "con-", root: "sequ / secu", suffix: "-ence", word: "consequence", meaning: "結果", etymology: "「共に」＋「続く」＋「こと」 → ある出来事と共に続いて起こること。" },
    { prefix: "con-", root: "sta / sist / stit", suffix: "-ent", word: "consistent", meaning: "一貫した", etymology: "「共に」＋「立つ」＋「性質の」 → 全てが共に成り立っている状態。" },
    { prefix: "contra-", root: "dic / dict", suffix: "none", word: "contradict", meaning: "矛盾する", etymology: "「反対に」＋「言う」 → 反対のことを言うこと。" },
    { prefix: "de-", root: "fin", suffix: "none", word: "define", meaning: "定義する", etymology: "「完全に」＋「境界を定める」 → 意味の範囲を明確にすること。" },
    { prefix: "de-", root: "grad / gress", suffix: "-ate", word: "degrade", meaning: "悪化させる", etymology: "「下に」＋「歩む」＋「させる」 → 段階を下に落とすこと。" },
    { prefix: "de-", root: "ject", suffix: "none", word: "deject", meaning: "落胆させる", etymology: "「下に」＋「投げる」 → 気分を下に投げ落とすこと。" },
    { prefix: "de-", root: "pend / pens", suffix: "none", word: "depend", meaning: "依存する", etymology: "「下に」＋「ぶら下がる」 → 何かに寄りかかり、頼ること。" },
    { prefix: "de-", root: "pon / posit / pose", suffix: "none", word: "deposit", meaning: "預金", etymology: "「下に」＋「置く」 →下に置いておくお金や物のこと。" },
    { prefix: "de-", root: "scrib / script", suffix: "none", word: "describe", meaning: "描写する", etymology: "「下に」＋「書く」 → 詳細に書き下すこと。" },
    { prefix: "dis-", root: "mit / miss", suffix: "none", word: "dismiss", meaning: "解散させる", etymology: "「離れて」＋「送る」 → バラバラの方向へ行かせること。" },
    { prefix: "dis-", root: "rupt", suffix: "none", word: "disrupt", meaning: "中断させる", etymology: "「分離して」＋「壊す」 → 流れを壊して中断させる。" },
    { prefix: "dis-", root: "tract", suffix: "none", word: "distract", meaning: "気を散らす", etymology: "「離れて」＋「引く」 → 注意を別の方向へ引き離すこと。" },
    { prefix: "e-", root: "ject", suffix: "none", word: "eject", meaning: "排出する", etymology: "「外に」＋「投げる」 → 外に投げ出すこと。" },
    { prefix: "e-", root: "rupt", suffix: "none", word: "erupt", meaning: "噴火する", etymology: "「外に」＋「壊す」 → 内から外へ破壊的に出ること。" },
    { prefix: "ex-", root: "cap / cept / ceive", suffix: "-ion", word: "exception", meaning: "例外", etymology: "「外に」＋「取る」＋「こと」 → ルールの中から外に取り出すこと。" },
    { prefix: "ex-", root: "ced / ceed / cess", suffix: "none", word: "exceed", meaning: "超える", etymology: "「外に」＋「進む」 → 限界の外に進み出ること。" },
    { prefix: "ex-", root: "clud / clus", suffix: "none", word: "exclude", meaning: "除外する", etymology: "「外に」＋「閉じる」 → 閉め出して外に置くこと。" },
    { prefix: "ex-", root: "pel / puls", suffix: "none", word: "expel", meaning: "追い出す", etymology: "「外に」＋「追い出す」 → 外へ追い出すこと。" },
    { prefix: "ex-", root: "pon / posit / pose", suffix: "none", word: "expose", meaning: "さらす", etymology: "「外に」＋「置く」 → 外に置いて見えるようにすること。" },
    { prefix: "ex-", root: "port", suffix: "none", word: "export", meaning: "輸出する", etymology: "「外に」＋「運ぶ」 → 外に運び出すこと。" },
    { prefix: "ex-", root: "tend / tens / tent", suffix: "none", word: "extend", meaning: "延長する", etymology: "「外に」＋「伸ばす」 → 範囲などを外へ広げる。" },
    { prefix: "ex-", root: "tract", suffix: "none", word: "extract", meaning: "抽出する", etymology: "「外に」＋「引く」 → 外へ引き出すこと。" },
    { prefix: "in-", root: "clud / clus", suffix: "none", word: "include", meaning: "含む", etymology: "「中に」＋「閉じる」 → 中に閉じ込めて含めること。" },
    { prefix: "in-", root: "fin", suffix: "-ite", word: "infinite", meaning: "無限の", etymology: "「否定」＋「終わり」＋「の」 → 終わりがないこと。" },
    { prefix: "in-", root: "form", suffix: "-al", word: "informal", meaning: "非公式の", etymology: "「否定」＋「形」＋「性質の」 → 決まった形式ではないこと。" },
    { prefix: "in-", root: "ject", suffix: "none", word: "inject", meaning: "注射する", etymology: "「中に」＋「投げる」 → 体内へ投げ込むこと。" },
    { prefix: "in-", root: "scrib / script", suffix: "none", word: "inscribe", meaning: "刻む", etymology: "「中に」＋「書く」 → 石や金属などに書き込むこと。" },
    { prefix: "in-", root: "spect", suffix: "-or", word: "inspector", meaning: "検査官", etymology: "「中に」＋「見る」＋「人」 → 内部を詳しく見る人。" },
    { prefix: "in-", root: "sta / sist / stit", suffix: "none", word: "insist", meaning: "主張する", etymology: "「中に」＋「立つ」 → 自分の意見の中にしっかりと立つこと。" },
    { prefix: "in-", root: "tend / tens / tent", suffix: "none", word: "intend", meaning: "意図する", etymology: "「中に」＋「伸ばす」 → 心を内側から特定の方向へ伸ばすこと。" },
    { prefix: "in-", root: "vis / vid", suffix: "-able", word: "invisible", meaning: "見えない", etymology: "「否定」＋「見る」＋「できる」 → 見ることができない。" },
    { prefix: "inter-", root: "act", suffix: "-ion", word: "interaction", meaning: "相互作用", etymology: "「間に」＋「行う」＋「こと」 → お互いの間で行うこと。" },
    { prefix: "inter-", root: "rupt", suffix: "none", word: "interrupt", meaning: "邪魔をする", etymology: "「間に」＋「壊す」 → 間に割って入って壊す。" },
    { prefix: "inter-", root: "ven / vent", suffix: "-ion", word: "intervention", meaning: "介入", etymology: "「間に」＋「来る」＋「こと」 → 物事の間に割って入ってくること。" },
    { prefix: "intro-", root: "duc / duct", suffix: "none", word: "introduce", meaning: "紹介する", etymology: "「内側へ」＋「導く」 → 輪の中へ導き入れること。" },
    { prefix: "intro-", root: "spect", suffix: "none", word: "introspect", meaning: "内省する", etymology: "「内側へ」＋「見る」 → 自分の心の内側を見ること。" },
    { prefix: "none", root: "act", suffix: "-ive", word: "active", meaning: "活動的な", etymology: "「行う」＋「性質を持つ」 → よく動く性質。" },
    { prefix: "none", root: "fin", suffix: "-al", word: "final", meaning: "最後の", etymology: "「終わり」＋「の性質の」 → 終わりの性質を持つ。" },
    { prefix: "none", root: "leg", suffix: "-al", word: "legal", meaning: "合法の", etymology: "「法律」＋「の性質の」 → 法律に関する。" },
    { prefix: "none", root: "port", suffix: "-able", word: "portable", meaning: "携帯可能な", etymology: "「運ぶ」＋「できる」 → 運ぶことができる。" },
    { prefix: "none", root: "vis / vid", suffix: "-al", word: "visual", meaning: "視覚の", etymology: "「見る」＋「性質の」 → 見ることに関する性質。" },
    { prefix: "ob-", root: "ject", suffix: "none", word: "object", meaning: "反対する", etymology: "「～に対して」＋「投げる」 → 意見などに対して投げ返すこと。" },
    { prefix: "ob-", root: "sta / sist / stit", suffix: "-acle", word: "obstacle", meaning: "障害物", etymology: "「～に対して」＋「立つ」＋「もの」 → 行く手に対して立っているもの。" },
    { prefix: "per-", root: "cap / cept / ceive", suffix: "none", word: "perceive", meaning: "知覚する", etymology: "「完全に」＋「取る」 → 物事を完全にとらえること。" },
    { prefix: "per-", root: "form", suffix: "none", word: "perform", meaning: "実行する", etymology: "「完全に」＋「形作る」 → 形を完全に成し遂げること。" },
    { prefix: "per-", root: "sta / sist / stit", suffix: "none", word: "persist", meaning: "固執する", etymology: "「完全に」＋「立つ」 → 完全に立ち続けること。" },
    { prefix: "pre-", root: "ced / ceed / cess", suffix: "none", word: "precede", meaning: "先行する", etymology: "「前に」＋「行く」 → 先に行くこと。" },
    { prefix: "pre-", root: "clud / clus", suffix: "none", word: "preclude", meaning: "排除する", etymology: "「前に」＋「閉じる」 → 前もって道を閉ざすこと。" },
    { prefix: "pre-", root: "dic / dict", suffix: "none", word: "predict", meaning: "予言する", etymology: "「前に」＋「言う」 → 前もって言うこと。" },
    { prefix: "pre-", root: "fer", suffix: "none", word: "prefer", meaning: "～の方を好む", etymology: "「前に」＋「運ぶ」 → 他より前に持ってきたいと思うこと。" },
    { prefix: "pre-", root: "scrib / script", suffix: "none", word: "prescribe", meaning: "処方する", etymology: "「前に」＋「書く」 → 前もって書き記すこと（処方箋など）。" },
    { prefix: "pre-", root: "ven / vent", suffix: "none", word: "prevent", meaning: "防ぐ", etymology: "「前に」＋「来る」 → 事が起こる前に来て防ぐこと。" },
    { prefix: "pro-", root: "ced / ceed / cess", suffix: "none", word: "proceed", meaning: "前進する", etymology: "「前に」＋「進む」 → 前に進むこと。" },
    { prefix: "pro-", root: "duc / duct", suffix: "none", word: "produce", meaning: "生産する", etymology: "「前に」＋「導く」 → 前に導き出すこと、生み出すこと。" },
    { prefix: "pro-", root: "grad / gress", suffix: "none", word: "progress", meaning: "進歩", etymology: "「前に」＋「歩む」 → 前へ歩み進むこと。" },
    { prefix: "pro-", root: "ject", suffix: "none", word: "project", meaning: "計画する", etymology: "「前に」＋「投げる」 → アイデアなどを前へ投げかけること。" },
    { prefix: "pro-", root: "mov / mot", suffix: "-ion", word: "promotion", meaning: "昇進", etymology: "「前に」＋「動かす」＋「こと」 → 地位などを前へ動かすこと。" },
    { prefix: "pro-", root: "pel / puls", suffix: "none", word: "propel", meaning: "推進する", etymology: "「前に」＋「進める」 → 前方へ推し進める。" },
    { prefix: "pro-", root: "pon / posit / pose", suffix: "none", "word": "propose", "meaning": "提案する", "etymology": "「前に」＋「置く」 → 考えを人の前に置くこと。" },
    { prefix: "pro-", root: "spect", suffix: "none", word: "prospect", meaning: "見込み", etymology: "「前に」＋「見る」 → 将来を見通すこと。" },
    { prefix: "pro-", root: "vis / vid", suffix: "-ion", word: "provision", meaning: "備え", etymology: "「前に」＋「見る」＋「こと」 → 将来を前もって見て備えること。" },
    { prefix: "pro-", root: "voc / voke", suffix: "none", word: "provoke", meaning: "挑発する", etymology: "「前に」＋「呼ぶ」 → 感情などを前に呼び出すこと。" },
    { prefix: "re-", root: "cap / cept / ceive", suffix: "none", word: "receive", meaning: "受け取る", etymology: "「後ろへ」＋「取る」 → 自分のところへ取り込むこと。" },
    { prefix: "re-", root: "ced / ceed / cess", suffix: "none", word: "recess", meaning: "休憩", etymology: "「後ろへ」＋「行く」 → 仕事などから後ろへ下がること。" },
    { prefix: "re-", root: "duc / duct", suffix: "none", word: "reduce", meaning: "減らす", etymology: "「後ろへ」＋「導く」 → 後ろへ引き戻すこと。" },
    { prefix: "re-", root: "fer", suffix: "none", word: "refer", meaning: "言及する", etymology: "「再び」＋「運ぶ」 → 何度もそこに話を持っていくこと。" },
    { prefix: "re-", root: "form", suffix: "none", word: "reform", meaning: "改革する", etymology: "「再び」＋「形作る」 → 新しく形作り直すこと。" },
    { prefix: "re-", root: "ject", suffix: "-ion", word: "rejection", meaning: "拒絶", etymology: "「後ろへ」＋「投げる」＋「こと」 → 投げ返すこと。" },
    { prefix: "re-", root: "mov / mot", suffix: "none", word: "remove", meaning: "取り除く", etymology: "「再び、後ろへ」＋「動かす」 → 元の場所から動かし去ること。" },
    { prefix: "re-", root: "pel / puls", suffix: "none", word: "repel", meaning: "追い払う", etymology: "「後ろへ」＋「押す」 → 押し返すこと。" },
    { prefix: "re-", root: "port", suffix: "none", word: "report", meaning: "報告する", etymology: "「後ろへ」＋「運ぶ」 → 見聞きしたことを持ち帰って伝えること。" },
    { prefix: "re-", root: "spect", suffix: "none", word: "respect", meaning: "尊敬する", etymology: "「再び」＋「見る」 → 何度も振り返って見ること。" },
    { prefix: "re-", root: "tain / ten", suffix: "none", word: "retain", meaning: "保持する", etymology: "「後ろに」＋「保つ」 → 後ろに引き止めて保つこと。" },
    { prefix: "re-", root: "tract", suffix: "none", word: "retract", meaning: "撤回する", etymology: "「後ろへ」＋「引く」 → 言ったことを引き戻すこと。" },
    { prefix: "re-", root: "vert / vers", suffix: "none", word: "revert", meaning: "元に戻る", etymology: "「再び」＋「向ける」 → 元の状態に再び向き直ること。" },
    { prefix: "re-", root: "vis / vid", suffix: "-ion", word: "revision", meaning: "改訂", etymology: "「再び」＋「見る」＋「こと」 → もう一度見直すこと。" },
    { prefix: "se-", root: "ced / ceed / cess", suffix: "none", word: "secede", meaning: "脱退する", etymology: "「離れて」＋「行く」 → グループから離れて行くこと。" },
    { prefix: "se-", root: "clud / clus", suffix: "none", word: "seclude", meaning: "隔離する", etymology: "「離れて」＋「閉じる」 → 他から離して閉じ込めること。" },
    { prefix: "se-", root: "duc / duct", suffix: "none", word: "seduce", meaning: "誘惑する", etymology: "「離れて」＋「導く」 → 正しい道から離れたところへ導くこと。" },
    { prefix: "sub-", root: "ject", suffix: "none", word: "subject", meaning: "主題、影響下の", etymology: "「下に」＋「投げる」 → 議論の土台に投げられたもの。" },
    { prefix: "sub-", root: "mit / miss", suffix: "none", word: "submit", meaning: "提出する", etymology: "「下に」＋「送る」 → 下から上へ差し出すこと。" },
    { prefix: "sub-", root: "scrib / script", suffix: "none", word: "subscribe", meaning: "定期購読する", etymology: "「下に」＋「書く」 → 書類の下に署名することから。" },
    { prefix: "sub-", root: "tract", suffix: "none", word: "subtract", meaning: "引き算する", etymology: "「下に」＋「引く」 → 下に取り去ること。" },
    { prefix: "super-", root: "vis / vid", suffix: "none", word: "supervise", meaning: "監督する", etymology: "「上に」＋「見る」 → 上から見ること。" },
    { prefix: "syn-", root: "chron", suffix: "-ize", word: "synchronize", meaning: "同期させる", etymology: "「共に」＋「時間」＋「～にする」 → 時間を共に合わせること。" },
    { prefix: "trans-", root: "act", suffix: "-ion", word: "transaction", meaning: "取引", etymology: "「越えて」＋「行う」＋「こと」 → 互いの間を行き来して行われること。" },
    { prefix: "trans-", root: "fer", suffix: "none", word: "transfer", meaning: "移す", etymology: "「越えて」＋「運ぶ」 → 向こう側へ運ぶこと。" },
    { prefix: "trans-", root: "form", suffix: "none", word: "transform", meaning: "変形させる", etymology: "「越えて」＋「形作る」 → 形の向こう側へ変えること。" },
    { prefix: "trans-", root: "mit / miss", suffix: "none", word: "transmit", meaning: "送信する", etymology: "「越えて」＋「送る」 → 向こう側へ送ること。" },
    { prefix: "trans-", root: "port", suffix: "-ion", word: "transportation", meaning: "輸送", etymology: "「越えて」＋「運ぶ」＋「こと」 → ある場所から別の場所へ運ぶこと。" },
    { prefix: "un-", root: "sta / sist / stit", suffix: "-able", word: "unstable", meaning: "不安定な", etymology: "「否定」＋「立つ」＋「できる」 → しっかり立つことができない。" },
  ]
};